version: "3.8"

services:
  app:
    build: 
      dockerfile: Dockerfile
    container_name:  "StudentRegistryExercise"
    image: qceka88/my-student-registry:v01
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=production